services:
  netns:
    image: k8s.gcr.io/pause:3.9
    container_name: pirate-netns
    restart: unless-stopped
    ports:
      - 64646:64646
      - 63636:63636

  corsa-node:
    restart: unless-stopped
    build:
      context: https://github.com/piratecash/corsa.git#v1.0.47
    container_name: corsa-node
    environment:
      CORSA_LISTEN_ADDRESS: "${CORSA_LISTEN_ADDRESS:-:64646}"
      CORSA_BOOTSTRAP_PEERS: "${CORSA_BOOTSTRAP_PEERS:-65.108.204.190:64646}"
      CORSA_RPC_HOST: "${CORSA_RPC_HOST:-0.0.0.0}"
      CORSA_RPC_PORT: "${CORSA_RPC_PORT:-46464}"
      CORSA_RPC_USERNAME: "${CORSA_RPC_USERNAME:-}"
      CORSA_RPC_PASSWORD: "${CORSA_RPC_PASSWORD:-}"
    network_mode: service:netns
    volumes:
      - corsa-data:/home/corsa/.corsacore

  pirate:
    restart: unless-stopped
    command: /usr/local/bin/piratecashd
    build: piratecash-main
    container_name: pirate
    depends_on:
      - corsa-node
    network_mode: service:netns
    volumes:
      - /opt/node/piratecash:/home/pirate/.piratecore/

volumes:
  corsa-data:
